FROM docker.io/library/postgres:17

RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-17-q3c \
    && rm -rf /var/lib/apt/lists/*

COPY 10-relphot-roles.sh /docker-entrypoint-initdb.d/10-relphot-roles.sh
RUN chmod 0755 /docker-entrypoint-initdb.d/10-relphot-roles.sh
