BASIS_TYPE      PIXEL_AUTO
BASIS_NUMBER    20
PSF_SAMPLING    1.0
PSF_PIXELSIZE   1.0
PSF_ACCURACY    0.01
PSF_SIZE        35,35
CENTER_KEYS     XWIN_IMAGE,YWIN_IMAGE
PHOTFLUX_KEY    FLUX_APER(1)
PHOTFLUXERR_KEY FLUXERR_APER(1)
PSFVAR_KEYS     X_IMAGE,Y_IMAGE
PSFVAR_GROUPS   1,1
PSFVAR_DEGREES  2
SAMPLE_AUTOSELECT Y
SAMPLEVAR_TYPE  NONE
SAMPLE_FWHMRANGE 2.0,12.0
SAMPLE_VARIABILITY 0.2
SAMPLE_MINSN    250
SAMPLE_MAXELLIP 0.3
SAMPLE_FLAGMASK 0x00fe
BADPIXEL_FILTER N
BADPIXEL_NMAX   0
HOMOBASIS_TYPE  NONE
STABILITY_TYPE  EXPOSURE
PSF_DIR         .
CHECKPLOT_TYPE  NONE
CHECKIMAGE_TYPE NONE
XML_NAME psfex.xml
WRITE_XML       N
NTHREADS        1
VERBOSE_TYPE    QUIET
