#!/usr/bin/env python3
"""Build tests/data from real T80S frames.

Run once, from the repository root, with the same interpreter used to run
the test suite (needs astropy):

    python3 tests/generate_fixtures.py

For the first 4 frames (by filename) of /ssdsto1/data/T80S_reduced/20251104/,
writes a small FITS file holding the real primary header (SCI/ERR/DQ/WEIGHT
as NAXIS=0 stand-ins, so their headers -- and hence the HDU order and names a
real MEF has -- are preserved without the ~1.3 GB of pixel data) plus the
real CATALOG rows restricted to a 1000x1000 px sky box, and CATFLAGS
untouched (it is tiny and irrelevant to relphot, kept only for fidelity to
the real HDU list). A matching CSV, cropped to the same box, is written
alongside it with the naming convention relphot.ingest expects
(``<stem>_proc.fits`` / ``<stem>_proc_catalog.csv``).

Not part of the test suite itself (pytest does not import or invoke this
module) -- tests/data is checked in once, generated by hand when the fixture
needs to change.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from astropy.io import fits
from astropy.table import Table

SOURCE_DIR = Path("/ssdsto1/data/T80S_reduced/20251104")
N_FRAMES = 4
BOX = (4000.0, 4500.0, 4000.0, 4500.0)  # xmin, xmax, ymin, ymax, in X_IMAGE/Y_IMAGE px
OUT_DIR = Path(__file__).parent / "data"

#: Header cards that describe pixel-array structure, not frame metadata; these
#: must never be copied onto a NAXIS=0 stand-in HDU (fits.ImageHDU already
#: sets them correctly for an empty array, and re-adding them would create a
#: header that lies about the data it goes with).
_STRUCTURAL_CARDS = {
    "SIMPLE", "BITPIX", "NAXIS", "NAXIS1", "NAXIS2", "EXTEND", "PCOUNT", "GCOUNT", "XTENSION",
}


def _strip_structural(header: fits.Header) -> fits.Header:
    stripped = header.copy()
    for card in _STRUCTURAL_CARDS:
        stripped.pop(card, None)
    return stripped


def _crop_fits(src: Path, dst: Path) -> int:
    with fits.open(src, memmap=True) as hdul:
        primary_header = hdul[0].header.copy()
        cat_hdu = hdul["CATALOG"]
        cat_header = cat_hdu.header.copy()
        cat_table = Table(cat_hdu.data)
        catflags_data = hdul["CATFLAGS"].data.copy()
        catflags_header = hdul["CATFLAGS"].header.copy()
        image_headers = {
            name: _strip_structural(hdul[name].header) for name in ("SCI", "ERR", "DQ", "WEIGHT")
        }

    xmin, xmax, ymin, ymax = BOX
    x = np.asarray(cat_table["X_IMAGE"])
    y = np.asarray(cat_table["Y_IMAGE"])
    box_mask = (x >= xmin) & (x < xmax) & (y >= ymin) & (y < ymax)
    cropped = cat_table[box_mask]

    hdus: list[fits.hdu.base._BaseHDU] = [fits.PrimaryHDU(header=_strip_structural(primary_header))]
    for name, header in image_headers.items():
        hdus.append(fits.ImageHDU(data=None, header=header, name=name))
    cat_out = fits.BinTableHDU(data=cropped, header=cat_header, name="CATALOG")
    hdus.append(cat_out)
    hdus.append(fits.BinTableHDU(data=catflags_data, header=catflags_header, name="CATFLAGS"))

    fits.HDUList(hdus).writeto(dst, overwrite=True)
    return len(cropped)


def _crop_csv(src: Path, dst: Path) -> int:
    table = Table.read(src, format="ascii.csv")
    xmin, xmax, ymin, ymax = BOX
    x = np.asarray(table["X_IMAGE"])
    y = np.asarray(table["Y_IMAGE"])
    box_mask = (x >= xmin) & (x < xmax) & (y >= ymin) & (y < ymax)
    cropped = table[box_mask]
    cropped.write(dst, format="ascii.csv", overwrite=True)
    return len(cropped)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    fits_files = sorted(str(p) for p in SOURCE_DIR.glob("*_proc.fits"))[:N_FRAMES]
    if len(fits_files) < N_FRAMES:
        msg = f"expected >= {N_FRAMES} frames under {SOURCE_DIR}, found {len(fits_files)}"
        raise SystemExit(msg)

    for fits_path in fits_files:
        stem = Path(fits_path).name.removesuffix(".fits")  # e.g. TOO-..._proc
        csv_path = Path(fits_path).with_name(stem + "_catalog.csv")

        dst_fits = OUT_DIR / f"{stem}.fits"
        dst_csv = OUT_DIR / f"{stem}_catalog.csv"

        n_fits = _crop_fits(Path(fits_path), dst_fits)
        n_csv = _crop_csv(csv_path, dst_csv)
        print(f"{stem}: {n_fits} FITS rows, {n_csv} CSV rows -> {dst_fits.name}, {dst_csv.name}")


if __name__ == "__main__":
    main()
